// Generated by CoffeeScript 1.3.1
(function() {
  var Proggis, _ref;

  Proggis = (_ref = window.Proggis) != null ? _ref : window.Proggis = {};

  Proggis.Info = {
    show: function(route) {
      switch (route) {
        case "route:home":
          return jQuery.get("_list/tables/execDocs", function(tableHtml) {
            jQuery("article .data").html(tableHtml);
            jQuery('.data table td.date').each(function() {
              jQuery(this).attr('title', jQuery(this).text());
              return jQuery(this).prettyDate();
            });
            return jQuery("article .data tr").click(function() {
              var id;
              id = jQuery(this).attr("about");
              return Proggis.router.navigate("execution/" + id + "/", true);
            });
          }, "text");
        default:
          return jQuery("article .data").html("");
      }
    },
    showDocsByExecId: function(execId) {
      Proggis.db.openDoc(execId, {
        success: function(doc) {
          var tmpl;
          tmpl = "<div>\n    <p>The execution of the workflow <b>${workflow}</b> begun <b class=\"date\">${start}</b>\n    and ended <b class=\"date\">${start}</b>. The current state is <b>\"${state}\"</b>.</p>\n    <p>The imported data objects were the following:</p>\n    <button id=\"accept\">Accept</button>\n    <button id=\"decline\">Decline</button>\n<div>";
          Proggis.description.html("");
          jQuery(tmpl).tmpl(doc).appendTo(Proggis.description);
          jQuery(".date", Proggis.description).prettyDate();
          jQuery("button", Proggis.description).button();
          jQuery("#accept").click(function(e) {
            return console.log("accepted");
          });
          return jQuery("#decline").click(function(e) {
            return console.log("declined");
          });
        }
      });
      Proggis.viewName.html("Execution document");
      return jQuery.get("_list/tables/DocumentsByExecution?startkey=[\"" + execId + "\"]&endkey=[\"" + execId + "a\"]", function(tablesHtml) {
        jQuery('.graph').hide();
        if (tablesHtml.length) {
          return jQuery("article .data").html(tablesHtml);
        } else {
          return jQuery("article .data").html("<h1>No documents in the list</h1>");
        }
      }, "text");
    }
  };

}).call(this);
