// Generated by CoffeeScript 1.3.1
(function() {
  var Proggis, _ref;

  Proggis = (_ref = window.Proggis) != null ? _ref : window.Proggis = {};

  Proggis.Navigation = {
    getIds: function(callback) {
      var ids;
      ids = [];
      jQuery("header nav ol li a").each(function() {
        if (!jQuery(this).attr("id")) {
          return;
        }
        return ids.push(jQuery(this).attr("id"));
      });
      return callback(ids);
    },
    handleRouteChange: function(route) {
      var nav;
      nav = Proggis.Navigation;
      jQuery("header nav ol li a").removeClass("active");
      return nav.getIds(function(ids) {
        var id, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = ids.length; _i < _len; _i++) {
          id = ids[_i];
          if (route.indexOf(id) === -1) {
            continue;
          }
          _results.push(jQuery("#" + id).addClass("active"));
        }
        return _results;
      });
    }
  };

}).call(this);
