// Generated by CoffeeScript 1.3.1
(function() {
  var Proggis, _ref;

  Proggis = (_ref = window.Proggis) != null ? _ref : window.Proggis = {};

  Proggis.db = $.couch.db("default");

  Proggis.showEditableDescription = function(route) {
    switch (route) {
      case "route:execution":
        return console.log("no editable description for", route);
      case "route:home":
        Proggis.description.attr("route", route);
        return Proggis.description.html("Interactive Knowledge Stack (IKS) is an open source community, whose projects are focused on building an open and flexible technology platform for semantically enhanced Content Management Systems (CMS).");
      default:
        Proggis.description.attr("route", route);
        return Proggis.description.html("The default editable text...");
    }
  };

  jQuery(document).ready(function() {
    Proggis.viewName = jQuery("#viewName");
    Proggis.graph = jQuery('.graph');
    Proggis.visualization = jQuery('#visualization');
    Proggis.description = jQuery(".info.description");
    $('#loadingSpinner').hide().ajaxStart(function() {
      return $(this).show();
    }).ajaxStop(function() {
      return $(this).hide();
    });
    Proggis.description.hallo({
      plugins: {
        halloformat: {}
      },
      modified: function() {
        return console.log("description edited", this);
      }
    });
    return Proggis.scrollTo = function(selector) {
      var curtop, obj;
      obj = jQuery(selector)[0];
      curtop = obj.offsetTop;
      while (obj = obj.offsetParent) {
        curtop += obj.offsetTop;
      }
      return window.scrollTo(0, curtop);
    };
  });

}).call(this);
